root = "."
tmp_dir = "tmp"

[build]
  cmd = "go tool templ generate && pnpm build:css && go build -o tmp/main ."
  bin = "tmp/main"
  include_ext = ["go", "templ"]
  exclude_regex = ["_templ\\.go"]
  delay = 100

[run]
  stop_signal = "SIGTERM"
  stop_timeout = 5000

[log]
  time = true

[misc]
  clean_on_exit = true
