// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ThemeToggle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<label class=\"toggle text-base-content\"><input id=\"theme-controller\" type=\"checkbox\" class=\"theme-controller\"> <span class=\"sr-only\">Toggle dark mode</span></label><script>\n\t\tconst prefersDark = window.matchMedia(\"(prefers-color-scheme: dark)\").matches;\n\t\tconst stored = localStorage.getItem(\"theme\");\n\t\tconst theme = stored || prefersDark ? \"mydark\" : \"mylight\"\n\t\tconst themeController = document.getElementById(\"theme-controller\");\n\n\t\tthemeController.value = theme === \"mydark\" ? \"mylight\" : \"mydark\"\n\n\t\tif (stored === themeController.value) {\n\t\t\tthemeController.checked = true;\n\t\t}\n\n\t\tthemeController.addEventListener(\"change\", (e) => {\n\t\t\tconst current = localStorage.getItem(\"theme\");\n\t\t\tlocalStorage.setItem(\"theme\", current === \"mydark\" ? \"mylight\" : \"mydark\");\n\t\t})\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
