name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/steven-dyson/personal-portfolio
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_STAGING_ENVIRONMENT_ID: ${{ secrets.RAILWAY_STAGING_ENVIRONMENT_ID }}
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Update Railway staging service with new image
        run: |
          curl -X POST https://backboard.railway.app/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
            -d '{
              "query": "mutation DeployImage($input: DeployImageInput!) { deployImage(input: $input) { id } }",
              "variables": {
                "input": {
                  "serviceId": "'"$RAILWAY_SERVICE_ID"'",
                  "environmentId": "'"$RAILWAY_STAGING_ENVIRONMENT_ID"'",
                  "image": "'"$IMAGE_NAME:latest"'"
                }
              }
            }'

  deploy-production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/your-image-name
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      RAILWAY_PRODUCTION_SERVICE_ID: ${{ secrets.RAILWAY_PRODUCTION_SERVICE_ID }}
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

    steps:
      - name: Deploy image to Railway production service
        run: |
          curl -X POST https://backboard.railway.app/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
            -d '{
              "query": "mutation DeployImage($input: DeployImageInput!) { deployImage(input: $input) { id } }",
              "variables": {
                "input": {
                  "serviceId": "'"$RAILWAY_PRODUCTION_SERVICE_ID"'",
                  "environmentId": "'"$RAILWAY_PRODUCTION_ENVIRONMENT_ID"'",
                  "image": "'"$IMAGE_NAME:latest"'"
                }
              }
            }'
