name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    env:
      IMAGE_NAME: ghcr.io/steven-dyson/personal-portfolio
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_STAGING_ENVIRONMENT_ID: ${{ secrets.RAILWAY_STAGING_ENVIRONMENT_ID }}
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Update Railway staging service with new image
        run: |
          curl -X POST https://backboard.railway.app/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
            -d '{
              "query": "mutation UpdateServiceImage($input: ServiceUpdateInput!) { serviceUpdate(input: $input) { id name source { image } } }",
              "variables": {
                "input": {
                  "projectId": "${{ secrets.RAILWAY_PROJECT_ID }}",
                  "environmentId": "'"$RAILWAY_STAGING_ENVIRONMENT_ID"'",
                  "serviceId": "'"$RAILWAY_SERVICE_ID"'",
                  "source": {
                    "image": "'"$IMAGE_NAME:latest"'"
                  }
                }
              }
            }'

      - name: Redeploy Railway staging service
        run: |
          curl -X POST https://backboard.railway.app/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
            -d '{
              "query": "mutation ServiceInstanceRedeploy { serviceInstanceRedeploy(environmentId: \"'"$RAILWAY_STAGING_ENVIRONMENT_ID"'\", serviceId: \"'"$RAILWAY_SERVICE_ID"'\") }",
              "variables": {}
            }'

  deploy-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    env:
      IMAGE_NAME: ghcr.io/steven-dyson/personal-portfolio
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      RAILWAY_PRODUCTION_SERVICE_ID: ${{ secrets.RAILWAY_PRODUCTION_SERVICE_ID }}
      RAILWAY_PRODUCTION_ENVIRONMENT_ID: ${{ secrets.RAILWAY_PRODUCTION_ENVIRONMENT_ID }}
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

    steps:
      - name: Update Railway production service with new image
        run: |
          curl -X POST https://backboard.railway.app/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
            -d '{
              "query": "mutation UpdateServiceImage($input: ServiceUpdateInput!) { serviceUpdate(input: $input) { id name source { image } } }",
              "variables": {
                "input": {
                  "projectId": "'"$RAILWAY_PROJECT_ID"'",
                  "environmentId": "'"$RAILWAY_PRODUCTION_ENVIRONMENT_ID"'",
                  "serviceId": "'"$RAILWAY_PRODUCTION_SERVICE_ID"'",
                  "source": {
                    "image": "'"$IMAGE_NAME:latest"'"
                  }
                }
              }
            }'

      - name: Redeploy Railway production service
        run: |
          curl -X POST https://backboard.railway.app/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
            -d '{
              "query": "mutation ServiceInstanceRedeploy { serviceInstanceRedeploy(environmentId: \"'"$RAILWAY_PRODUCTION_ENVIRONMENT_ID"'\", serviceId: \"'"$RAILWAY_PRODUCTION_SERVICE_ID"'\") }",
              "variables": {}
            }'
